### ISSUE TITLE
Parallel test failed when install firedrake by spack

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake-spack#20]
I install firedrake by adding the following package to spack env:
```
spack add py-firedrake@develop%gcc +64-bit-indices+complex  ^openblas \
    ^petsc+mumps+scalapack+int64+complex+libyaml+parmmg+mmg \
    ^hypre+complex+int64+superlu-dist && \
spack add py-pygmsh py-meshio py-tqdm py-pyyaml
```
`spack` finished the installation by using `openmpi`. 

When I test the installation by 
```
pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection" 2>&1
```
The parallel tests all failed.

Is this a known issue?

The spec of the env and the test log is attached.
[firedrake-pytest-log.txt](https://github.com/firedrakeproject/firedrake-spack/files/9898524/firedrake-pytest-log.txt)
[firedrake-spec.txt](https://github.com/firedrakeproject/firedrake-spack/files/9898517/firedrake-spec.txt)

Then I create a new spack env to install firedrake with `mpich`, the test fails again. The errors are a little different:
```
==================================== ERRORS ====================================
___________ ERROR at setup of test_poisson_analytic_linear_parallel ____________

item = <Function test_poisson_analytic_linear_parallel>

    def pytest_runtest_setup(item):
        if item.get_closest_marker("parallel"):
            from mpi4py import MPI
            if MPI.COMM_WORLD.size > 1:
                # Turn on source hash checking
                from firedrake import parameters
                from functools import partial

                def _reset(check):
                    parameters["pyop2_options"]["check_src_hashes"] = check

                # Reset to current value when test is cleaned up
>               item.addfinalizer(partial(_reset,
                                          parameters["pyop2_options"]["check_src_hashes"]))
E               AssertionError: (<Function test_poisson_analytic_linear_parallel>, {})

tests/conftest.py:82: AssertionError
=========================== short test summary info ============================
```
[firedrake-mpich-pytest.txt](https://github.com/firedrakeproject/firedrake-spack/files/9898607/firedrake-mpich-pytest.txt)

Thanks for your attention!

**Comment by connorjward** [comment]
I think you are getting this error because parallel tests are currently failing with pytest newer than 6.2.5. You are using 7.1.3 here. @JDBetteridge is currently working on a fix but I expect your error will go away if you downgrade your pytest version.

**Comment by JDBetteridge** [comment]
These issues should be fixed with [this](https://github.com/firedrakeproject/firedrake/pull/2606) PR. So far my work has just fixed the pytest failure, but my aim is to completely refactor the Firedrake parallel tests. You are welcome to try out that Firedrake branch to see if that resolves your issue also.

**Comment by lrtfm** [comment]
Thanks!

**Comment by lrtfm** [comment]
> These issues should be fixed with [this](https://github.com/firedrakeproject/firedrake/pull/2606) PR. So far my work has just fixed the pytest failure, but my aim is to completely refactor the Firedrake parallel tests. You are welcome to try out that Firedrake branch to see if that resolves your issue also.

I tested the mpich case. All the tests passed. Thanks!
