### ISSUE TITLE
Some options related to `64-bit-indices` and `complex`

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake-spack#6]
First, thank you for your team making this tool available. 

I try to install firedrake with this useful tool, and find some options that should be updated:
1. `+int64` of PETSc should be added if `+64-bit-indices` is turned on.
2. `+complex` of PETSc should be added if `+complex` is turned on.
3.  For PETSc `+chaco` is in conflict with `+int64`
4. `py-pybind11` is one of the dependencies of `firedrake.py-islpy`.

In addition, I have a question about `hypre`. It seems `hypre` has options `int64` and `complex`. If I want to use it in complex and int64 mode, must it be compiled in int64?

**Comment by JDBetteridge** [comment]
Thanks for pointing out these issues, I'm keeping track of the fixes [here](https://github.com/firedrakeproject/firedrake-spack/pull/5).

If you want to use hypre with complex problems and large problems thate require int64 indexing, you need to build PETSc with complex and int64 flags. PETSc _should_ then ensure hypre is installed correctly, as well as ensure compatibility with the rest of PETSc.
